version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: muchavidas-db
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: muchavidas
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d muchavidas"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
